services:
  airvpn:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file:
      - docker.env
      - .env
    ports:
      - 8080:8080 # qBittorrent WebUI
      # - 7878:7878 # Radarr WebUI
      # - 8989:8989 # Sonarr WebUI
      # - 6767:6767 # Bazarr WebUI
      # - 8686:8686 # Lidarr WebUI
      # - 9696:9696 # Prowlarr WebUI
    restart: unless-stopped
    networks:
      vpn:
        aliases:
          - gluetun
        ipv4_address: 192.168.100.2

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
      - WEBUI_PORT=8080
    volumes:
      - /home/gurek/Repos/media-servarr/configs/qbittorrent:/config
      - /home/gurek/media-servarr:/data
    depends_on:
      - airvpn
    network_mode: "service:airvpn"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /home/gurek/Repos/media-servarr/configs/radarr:/config
      - /home/gurek/media-servarr:/data
    depends_on:
      - qbittorrent
    network_mode: host
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /home/gurek/Repos/media-servarr/configs/sonarr:/config
      - /home/gurek/media-servarr:/data
    depends_on:
      - qbittorrent
    network_mode: host
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /home/gurek/Repos/media-servarr/configs/prowlarr:/config
    depends_on:
      - qbittorrent
    network_mode: host
    restart: unless-stopped

  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIMEZONE}
    volumes:
      - /home/gurek/Repos/media-servarr/configs/bazarr:/config
      - /home/gurek/media-servarr:/data
    depends_on:
      - qbittorrent
    network_mode: host
    restart: unless-stopped

  emby:
    image: emby/embyserver
    container_name: emby
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=${PUID}
      - GID=${PGID}
    volumes:
      - /home/gurek/Repos/media-servarr/configs/emby:/config # Configuration directory
      - /home/gurek/media-servarr:/data
    devices:
      - /dev/dri:/dev/dri # VAAPI/NVDEC/NVENC render nodes
    restart: on-failure

networks:
  vpn:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.100.0/24"
