services:
  airvpn:
    image: qmcgaw/gluetun
    container_name: gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    env_file:
      - docker.env
    ports:
      - 8080:8080 # qBittorrent WebUI
      - 7878:7878 # Radarr WebUI
      - 8989:8989 # Sonarr WebUI
      - 8686:8686 # Lidarr WebUI
      - 9696:9696 # Prowlarr WebUI
      - 5055:5055 # Overseerr WebUI
      - 7575:7575 # Homarr WebUI
    restart: unless-stopped
    networks:
      vpn:
        aliases:
          - gluetun
        ipv4_address: 192.168.100.2

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1001
      - PGID=545
      - TZ=Europe/Prague
      - WEBUI_PORT=8080
    volumes:
      - /home/gurek/Repos/media-servarr/configs/qbittorrent:/config
      - /home/gurek/Downloads/qbittorrent/media-servarr:/downloads
    depends_on:
      - airvpn
    network_mode: "service:airvpn"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=Europe/Prague
    volumes:
      - /home/gurek/Repos/media-servarr/configs/radarr:/config
      - /home/gurek/Media/movies:/movies
      - /home/gurek/Downloads/qbittorrent/media-servarr:/downloads
    depends_on:
      - airvpn
    network_mode: "service:airvpn"
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=Europe/Prague
    volumes:
      - /home/gurek/Repos/media-servarr/configs/sonarr:/config
      - /home/gurek/Downloads/qbittorrent/media-servarr:/downloads
      - /home/gurek/Media/tv:/tv
    depends_on:
      - airvpn
    network_mode: "service:airvpn"
    restart: unless-stopped

  lidarr:
    image: linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=Europe/Prague
    volumes:
      - /home/gurek/Repos/media-servarr/configs/lidarr:/config
      - /home/gurek/Downloads/qbittorrent/media-servarr:/downloads
      - /home/gurek/Media/music:/music
    depends_on:
      - airvpn
    network_mode: "service:airvpn"
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=Europe/Prague
    volumes:
      - /home/gurek/Repos/media-servarr/configs/prowlarr:/config
    depends_on:
      - airvpn
    network_mode: "service:airvpn"
    restart: unless-stopped

  overseerr:
    image: sctx/overseerr
    container_name: overseerr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=Europe/Prague
    volumes:
      - /home/gurek/Repos/media-servarr/configs/overseerr:/app/config
    depends_on:
      - airvpn
    network_mode: "service:airvpn"
    restart: unless-stopped

  homarr:
    image: ghcr.io/ajnart/homarr:latest
    container_name: homarr
    environment:
      - PUID=1001
      - PGID=545
      - TZ=Europe/Prague
    volumes:
      - /home/gurek/Repos/media-servarr/configs/homarr:/config
    depends_on:
      - airvpn
    network_mode: "service:airvpn"
    restart: unless-stopped

networks:
  vpn:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.100.0/24"
